"""empty message

Revision ID: 5582645285e2
Revises: 2e0d59f3025d
Create Date: 2023-01-24 18:50:28.678671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5582645285e2'
down_revision = '2e0d59f3025d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mass', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hair_color', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('skin_color', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('birth_year', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=250), nullable=True))

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diameter', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rotation_period', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('orbital_period', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gravity', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('population', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('climate', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('terrain', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('surface_water', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_column('surface_water')
        batch_op.drop_column('terrain')
        batch_op.drop_column('climate')
        batch_op.drop_column('population')
        batch_op.drop_column('gravity')
        batch_op.drop_column('orbital_period')
        batch_op.drop_column('rotation_period')
        batch_op.drop_column('diameter')

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('gender')
        batch_op.drop_column('birth_year')
        batch_op.drop_column('skin_color')
        batch_op.drop_column('hair_color')
        batch_op.drop_column('mass')
        batch_op.drop_column('height')

    # ### end Alembic commands ###
