"""empty message

Revision ID: 908b407e0aea
Revises: 94d1390e8912
Create Date: 2023-01-23 21:35:20.186103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '908b407e0aea'
down_revision = '94d1390e8912'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_characters', sa.Integer(), nullable=True),
    sa.Column('id_planets', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_characters'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['id_planets'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('dude_channel')
    op.drop_table('dude')
    op.drop_table('channel')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('channel_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='channel_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('dude',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('dude_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='dude_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('dude_channel',
    sa.Column('dude_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('channel_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], name='dude_channel_channel_id_fkey'),
    sa.ForeignKeyConstraint(['dude_id'], ['dude.id'], name='dude_channel_dude_id_fkey')
    )
    op.drop_table('favorites')
    op.drop_table('planets')
    op.drop_table('characters')
    # ### end Alembic commands ###
